spring:
  application:
    name: springboot-rabbitmq
  rabbitmq:
    addresses: 192.168.247.128
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-confirms: true
